[build]
  command = "npm run build && pip install -r requirements.txt && python app.py"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.9.18"
