services:
  - type: web
    name: anything-boes-chat
    env: python
    buildCommand: pip install -r requirements.txt && npm install && npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false